In [23]:
import numpy as np
import sympy as sy
sy.init_printing()

In [24]:
# Create a 3x1 numpy array
v = np.array([[1],[2],[3]])
# Print the shape, number of dimensions, and the data type of the array
v.shape, v.ndim, v.dtype

((3, 1), 2, dtype('int32'))

In [25]:
# Create a 3x1 sympy matrix
v_s = sy.Matrix([1, 2, 3])
v_s.shape, v_s

⎛        ⎡1⎤⎞
⎜        ⎢ ⎥⎟
⎜(3, 1), ⎢2⎥⎟
⎜        ⎢ ⎥⎟
⎝        ⎣3⎦⎠

In [26]:
# Create a 1x3 numpy array
w = np.array([[1, 2, 3]])
w.shape, w.ndim, w.dtype

((1, 3), 2, dtype('int32'))

In [27]:
# Create a 1x3 sympy matrix
w_s = sy.Matrix([[1, 2, 3]])
w_s.shape, w_s

((1, 3), [1  2  3])

In [28]:
# 次元を指定してnumpy配列を作成し転置（行列変換）する
v = np.array([1, 2, 3], ndmin=2).T
v

array([[1],
       [2],
       [3]])

In [29]:
# ベクトルの和
v = np.array([[1, 2]]).T
w = np.array([[3, -4]]).T
v + w

array([[ 4],
       [-2]])

In [30]:
v_s = sy.Matrix(v)
w_s = sy.Matrix(w)
v_s + w_s

⎡4 ⎤
⎢  ⎥
⎣-2⎦

In [31]:
# ベクトルのスカラー倍
c = 2
v = np.array([[3, 1, 4]]).T
c * v

array([[6],
       [2],
       [8]])

In [32]:
c = 3
v_s = sy.Matrix(v)
c * v_s

⎡9 ⎤
⎢  ⎥
⎢3 ⎥
⎢  ⎥
⎣12⎦

In [33]:
# v = xi+yj (iとjは基底ベクトル)
# (3, 2) = 3i + 2j ... i=(1, 0), j=(0, 1)

In [34]:
# ユークリッド内積 (u1*v1 + u2*v2 + u3*v3)
u = np.array([[-2, 3, 5]]).T
v = np.array([[6, 1, 0]]).T
np.vdot(u, v)

-9

In [35]:
u_s = sy.Matrix(u)
v_s = sy.Matrix(v)
u_s.dot(v_s)

-9

In [36]:
from scipy import linalg as sla

v = np.array([[9, 2, -6]]).T
# 2-ノルム, 最大値ノルム, 1-ノルム (ノルム＝ベクトルの長さ)
sla.norm(v), sla.norm(v, np.inf), sla.norm(v, 1)

(11.0, 9.0, 17.0)

In [37]:
v_s = sy.Matrix(v)
# 2-ノルム, 最大値ノルム, 1-ノルム
v_s.norm(), v_s.norm(sy.oo), v_s.norm(1)

(11, 9, 17)

In [38]:
u = np.array([[-2, 3, 5]]).T
v = np.array([[6, 1, 0]]).T
# ベクトルのノルム(長さ)を計算(|u||v|)
sla.norm(u), sla.norm(v)
# ユークリッド内積を計算(u・v)
np.vdot(u, v)
# ベクトル間の"角度の余弦"を計算(cosΘ = u・v / |u||v|)
c = np.vdot(u, v) / (sla.norm(u) * sla.norm(v))
# "角度の余弦"をラジアン角度に変換（np.clipでcosΘの範囲に制限を設け、np.arccosで逆余弦関数を適用）
angle = np.arccos(np.clip(c, -1, 1))
# ラジアン角度を度数に変換
np.rad2deg(angle)

103.88779964407195